name: all_in_one
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.3+4

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  built_collection: ^5.1.1
  buttons_tabbar: ^1.3.8
  calendar_date_picker2: ^0.5.5
  collection: any
  cron: ^0.6.0
  cupertino_icons: ^1.0.6
  d_chart: ^2.6.9
  dropdown_button2: ^2.3.9
  filesize: ^2.0.1
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  flutter_context_menu:
    git:
      url: https://github.com/guchengxi1994/flutter_context_menu
  flutter_layout_grid: ^2.0.6
  flutter_riverpod: ^2.5.1
  flutter_rust_bridge: 2.0.0-dev.31
  gauge_indicator: ^0.4.3
  icons_plus: ^5.0.0
  isar: ^3.1.0+1  # run `flutter pub run build_runner build` to generate codes
  isar_flutter_libs: ^3.1.0+1
  loading_indicator: ^3.1.1
  logging: ^1.2.0
  lunar: ^1.3.12
  path_provider: ^2.1.2
  riverpod: ^2.5.1
  rust_lib_all_in_one:
    path: rust_builder
  syncfusion_flutter_calendar: ^25.1.38  # needs syncfusion license
  time_duration_picker: 
    git:
      url: https://github.com/guchengxi1994/time-duration-picker
  timezone: ^0.9.2
  toastification: ^1.2.1
  window_manager: ^0.3.8
  
dev_dependencies:
  analyzer: ^6.4.1
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

dependency_overrides:  
  analyzer: ^6.4.1

deferred-components:
  - name: all-in-one
    libraries:
      - package:all_in_one/workboard/workboard_screen.dart
      - package:all_in_one/entry/entry_screen.dart
      - package:all_in_one/software_monitor/software_monitor_screen.dart
      - package:all_in_one/schedule/schedule_screen.dart
      - package:all_in_one/time_converter/time_converter_screen.dart

flutter:
  uses-material-design: true

  assets:
    - assets/icon.ico
    - assets/icon.png
    - assets/icons/

  fonts:
    - family: NotoSns
      fonts:
        - asset: assets/fonts/NotoSansSC-Bold.ttf

flutter_launcher_icons:  # flutter pub run flutter_launcher_icons
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon.png" 