name: all_in_one
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.10

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  appflowy_editor: ^2.4.0
  auto_size_text: ^3.0.0
  blurrycontainer: ^2.1.0
  built_collection: ^5.1.1
  buttons_tabbar: ^1.3.8
  calendar_date_picker2: ^0.5.5
  collection: any
  cron: ^0.6.0
  crypto: ^3.0.3
  cupertino_icons: ^1.0.6
  d_chart: ^2.6.9
  dio: ^5.4.1
  dropdown_button2: ^2.3.9
  field_suggestion: ^0.2.5
  file_selector: ^1.0.3
  filesize: ^2.0.1
  flutter:
    sdk: flutter
  flutter_colorpicker:
    git:
      url: https://github.com/mchome/flutter_colorpicker
      ref: master  # or 786d04363f587b818ce585d25b9c2bb62de95aba
  flutter_context_menu:
    git:
      url: https://github.com/guchengxi1994/flutter_context_menu
  flutter_expandable_fab: ^2.0.0
  flutter_flow_chart: 
    git:
      url: https://github.com/guchengxi1994/flutter_flow_chart
      ref: v0.0.1
  flutter_layout_grid: ^2.0.6
  flutter_math_fork: ^0.7.2
  flutter_riverpod: ^2.5.1
  flutter_rust_bridge: 2.0.0-dev.35
  flutter_tags_x: ^1.1.0
  gauge_indicator: ^0.4.3
  icons_plus: ^5.0.0
  isar: ^3.1.0+1  # run `flutter pub run build_runner build` to generate codes
  isar_flutter_libs: ^3.1.0+1
  just_the_tooltip: ^0.0.12
  langchain_lib:
    path: langchain_lib
  loading_animation_widget: ^1.2.1
  loading_indicator: ^3.1.1
  logging: ^1.2.0
  lunar: ^1.3.12
  markdown_widget: ^2.3.2+6
  path_provider: ^2.1.2
  pluto_grid: ^8.0.0
  riverpod: ^2.5.1
  rust_lib_all_in_one:
    path: rust_builder
  star_menu: ^3.1.4
  syncfusion_flutter_calendar: ^25.1.38  # needs syncfusion license
  time_duration_picker: 
    git:
      url: https://github.com/guchengxi1994/time-duration-picker
  timezone: ^0.9.2
  toastification: ^2.0.0
  uuid: ^4.4.0
  window_manager: ^0.3.8
  
dev_dependencies:
  analyzer: ^6.4.1
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

dependency_overrides:  
  analyzer: ^6.4.1
  intl: ^0.19.0

deferred-components:
  - name: all-in-one
    libraries:
      - package:all_in_one/workboard/workboard_screen.dart
      - package:all_in_one/entry/entry_screen.dart
      - package:all_in_one/software_monitor/software_monitor_screen.dart
      - package:all_in_one/schedule/schedule_screen.dart
      - package:all_in_one/time_converter/time_converter_screen.dart

flutter:
  uses-material-design: true

  assets:
    - assets/icon.ico
    - assets/icon.png
    - assets/icons/
    - assets/llm.json
    - assets/llm/

  fonts:
    - family: NotoSns
      fonts:
        - asset: assets/fonts/NotoSansSC-Bold.ttf
    - family: xing
      fonts:
        - asset: assets/fonts/WeiNiZhuYiLangManXingShu-2.ttf

flutter_launcher_icons:  # flutter pub run flutter_launcher_icons
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon.png" 